/**
 * Utility function to get country flag emoji based on country name
 * @param country - The country name
 * @returns The corresponding flag emoji or a generic flag if not found
 */
export const getCountryFlag = (country: string): string => {
    const flagMap: { [key: string]: string } = {
        'United States of America': '🇺🇸',
        'USA': '🇺🇸',
        'United Kingdom': '🇬🇧',
        'UK': '🇬🇧',
        'Canada': '🇨🇦',
        'Australia': '🇦🇺',
        'Germany': '🇩🇪',
        'France': '🇫🇷',
        'Italy': '🇮🇹',
        'Spain': '🇪🇸',
        'Brazil': '🇧🇷',
        'Mexico': '🇲🇽',
        'Japan': '🇯🇵',
        'South Korea': '🇰🇷',
        'China': '🇨🇳',
        'India': '🇮🇳',
        'Russia': '🇷🇺',
        'Netherlands': '🇳🇱',
        'Sweden': '🇸🇪',
        'Norway': '🇳🇴',
        'Denmark': '🇩🇰',
        'Finland': '🇫🇮',
        'Poland': '🇵🇱',
        'Czech Republic': '🇨🇿',
        'Hungary': '🇭🇺',
        'Romania': '🇷🇴',
        'Bulgaria': '🇧🇬',
        'Greece': '🇬🇷',
        'Turkey': '🇹🇷',
        'Israel': '🇮🇱',
        'South Africa': '🇿🇦',
        'Nigeria': '🇳🇬',
        'Egypt': '🇪🇬',
        'Morocco': '🇲🇦',
        'Tanzania': '🇹🇿',
        'Argentina': '🇦🇷',
        'Chile': '🇨🇱',
        'Colombia': '🇨🇴',
        'Peru': '🇵🇪',
        'Venezuela': '🇻🇪',
        'Ecuador': '🇪🇨',
        'Uruguay': '🇺🇾',
        'Paraguay': '🇵🇾',
        'Bolivia': '🇧🇴',
        'Thailand': '🇹🇭',
        'Philippines': '🇵🇭',
        'Indonesia': '🇮🇩',
        'Malaysia': '🇲🇾',
        'Singapore': '🇸🇬',
        'Vietnam': '🇻🇳',
        'Cambodia': '🇰🇭',
        'Laos': '🇱🇦',
        'Myanmar': '🇲🇲',
        'Bangladesh': '🇧🇩',
        'Pakistan': '🇵🇰',
        'Sri Lanka': '🇱🇰',
        'Nepal': '🇳🇵',
        'Bhutan': '🇧🇹',
        'Maldives': '🇲🇻',
        'Afghanistan': '🇦🇫',
        'Iran': '🇮🇷',
        'Iraq': '🇮🇶',
        'Saudi Arabia': '🇸🇦',
        'UAE': '🇦🇪',
        'United Arab Emirates': '🇦🇪',
        'Kuwait': '🇰🇼',
        'Qatar': '🇶🇦',
        'Bahrain': '🇧🇭',
        'Oman': '🇴🇲',
        'Yemen': '🇾🇪',
        'Jordan': '🇯🇴',
        'Lebanon': '🇱🇧',
        'Syria': '🇸🇾',
        'Cyprus': '🇨🇾',
        'Malta': '🇲🇹',
        'Iceland': '🇮🇸',
        'Ireland': '🇮🇪',
        'Portugal': '🇵🇹',
        'Belgium': '🇧🇪',
        'Switzerland': '🇨🇭',
        'Austria': '🇦🇹',
        'Luxembourg': '🇱🇺',
        'Monaco': '🇲🇨',
        'Liechtenstein': '🇱🇮',
        'Andorra': '🇦🇩',
        'San Marino': '🇸🇲',
        'Vatican': '🇻🇦',
        'Ukraine': '🇺🇦',
        'Belarus': '🇧🇾',
        'Moldova': '🇲🇩',
        'Lithuania': '🇱🇹',
        'Latvia': '🇱🇻',
        'Estonia': '🇪🇪',
        'Slovakia': '🇸🇰',
        'Slovenia': '🇸🇮',
        'Croatia': '🇭🇷',
        'Bosnia': '🇧🇦',
        'Serbia': '🇷🇸',
        'Montenegro': '🇲🇪',
        'North Macedonia': '🇲🇰',
        'Albania': '🇦🇱',
        'Kosovo': '🇽🇰',
        'Georgia': '🇬🇪',
        'Armenia': '🇦🇲',
        'Azerbaijan': '🇦🇿',
        'Kazakhstan': '🇰🇿',
        'Uzbekistan': '🇺🇿',
        'Kyrgyzstan': '🇰🇬',
        'Tajikistan': '🇹🇯',
        'Turkmenistan': '🇹🇲',
        'Mongolia': '🇲🇳',
        'North Korea': '🇰🇵',
        'Taiwan': '🇹🇼',
        'Hong Kong': '🇭🇰',
        'Macau': '🇲🇴',
        'New Zealand': '🇳🇿',
        'Fiji': '🇫🇯',
        'Papua New Guinea': '🇵🇬',
        'Samoa': '🇼🇸',
        'Tonga': '🇹🇴',
        'Vanuatu': '🇻🇺',
        'Solomon Islands': '🇸🇧',
        'Palau': '🇵🇼',
        'Micronesia': '🇫🇲',
        'Marshall Islands': '🇲🇭',
        'Kiribati': '🇰🇮',
        'Nauru': '🇳🇷',
        'Tuvalu': '🇹🇻',
        'Cuba': '🇨🇺',
        'Jamaica': '🇯🇲',
        'Haiti': '🇭🇹',
        'Dominican Republic': '🇩🇴',
        'Puerto Rico': '🇵🇷',
        'Trinidad and Tobago': '🇹🇹',
        'Barbados': '🇧🇧',
        'Saint Lucia': '🇱🇨',
        'Saint Vincent': '🇻🇨',
        'Grenada': '🇬🇩',
        'Antigua and Barbuda': '🇦🇬',
        'Saint Kitts and Nevis': '🇰🇳',
        'Dominica': '🇩🇲',
        'Belize': '🇧🇿',
        'Guatemala': '🇬🇹',
        'Honduras': '🇭🇳',
        'El Salvador': '🇸🇻',
        'Nicaragua': '🇳🇮',
        'Costa Rica': '🇨🇷',
        'Panama': '🇵🇦'
    };
    
    return flagMap[country] || '🏳️';
};
